"""3

Revision ID: 36ce5d613fec
Revises: d329262a27dc
Create Date: 2024-10-28 12:32:34.898711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
users = table(
    'users',
    column('hashed_password', sa.String),
)


# revision identifiers, used by Alembic.
revision: str = '36ce5d613fec'
down_revision: Union[str, None] = 'd329262a27dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.execute(
        users.update().values(hashed_password=sa.text("'temp_password'"))
    )
    # Делаем колонку `hashed_password` обязательной
    op.alter_column('users', 'hashed_password', nullable=False)
   

   


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
